### ISSUE TITLE
BUG Bot defaults to 25565 even if you tell it to use a different port.

### ISSUE THREAD

**Issue by johncsuti** [tedztar/mcstatusbot#23]
Config:
{
    "token":"HIDDEN",
    "commandPrefix":"/",
    "ip":"Play.64Stacks.com",
    "port":"25572",
    "pingInterval":"30",
    "embedColor":"7289DA"
}

Start up message:
Ping: Error getting server status
Error: connect ECONNREFUSED 45.20.152.169:25565
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '45.20.152.169',
  port: 25565

**Comment by johncsuti** [comment]
Also once i opened port 25565 it shows idle status even though my server has 1000 player cap and the current player count is 16???

**Comment by johncsuti** [comment]
johncsuti#0001 ran command: _help
Issuing help message.
(node:24551) UnhandledPromiseRejectionWarning: ReferenceError: Discord is not defined
    at Object.exports.run (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/commands/help.js:4:32)
    at Object.exports.run (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/events/message.js:19:15)
    at Client.<anonymous> (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/mcbot.js:63:53)
    at Client.emit (events.js:321:20)
    at MessageCreateHandler.handle (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:296:17)
    at WebSocket.onMessage (/home/youngdrummer98/minecraft-64stacks/mcstatusbot/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
(node:24551) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:24551) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by johncsuti** [comment]
Three bugs in one issue way to go me.

**Comment by tedztar** [comment]
> Also once i opened port 25565 it shows idle status even though my server has 1000 player cap and the current player count is 16???

Are you running bungee? If so I have not found a way to fully support bungee, I am still trying to find a way to do this tho.

**Comment by johncsuti** [comment]
Yes I am but that shouldn't affect the port do we know whats going on?

**Comment by johncsuti** [comment]
Does this also fix the issue where commands do not work as stated above?

**Comment by tedztar** [comment]
I have just made a change that should fix most issues, Please test and create a new bug if not working.
Thanks
