### ISSUE TITLE
Server is on, but it always times out when pinging

### ISSUE THREAD

**Issue by Maxidoos** [tedztar/mcstatusbot#26]
Here is the error:

[1:18:57 p.m.]: Ping: Error getting server status
Error: Socket timed out when connecting to 173.176.92.182:25583
    at Socket.<anonymous> (C:\Users\Maximilian\Documents\Aqua's Crazy World\mcstatusbot-0.2\mcstatusbot-0.2\node_modules\mc-ping-updated\lib\ping.js:50:13)
    at Object.onceWrapper (events.js:421:28)
    at Socket.emit (events.js:315:20)
    at Socket._onTimeout (net.js:481:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by tedztar** [comment]
Can you please update the code and see if that fixes the issue.

Thanks

**Comment by Maxidoos** [comment]
I updated the code, but the issue still occured, however i figured out why and fixed it. It was my fault. I put my public IP Address in the config, but then thought about how the bot is running on my computer, so I changed it to my private IP address and now it works. Sorry for bothering you!
