### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by AlphaStrix717** [tedztar/mcstatusbot#35]
This is the error it comes up with, I'm not sure how to fix it... Successfully loaded help.js
Successfully loaded ping.js
Successfully loaded status.js
Successfully loaded message.js
(node:9156) UnhandledPromiseRejectionWarning: Error: Incorrect login details were provided.
    at WebSocketConnection.<anonymous> (C:\Users\miche\Downloads\mcstatusbot-0.2 (2)\mcstatusbot-0.2\node_modules\discord.js\src\client\ClientManager.js:48:41)
    at Object.onceWrapper (events.js:422:26)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.onClose (C:\Users\miche\Downloads\mcstatusbot-0.2 (2)\mcstatusbot-0.2\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:390:10)
    at WebSocket.onClose (C:\Users\miche\Downloads\mcstatusbot-0.2 (2)\mcstatusbot-0.2\node_modules\ws\lib\event-target.js:124:16)
    at WebSocket.emit (events.js:315:20)
    at WebSocket.emitClose (C:\Users\miche\Downloads\mcstatusbot-0.2 (2)\mcstatusbot-0.2\node_modules\ws\lib\websocket.js:191:10)
    at TLSSocket.socketOnClose (C:\Users\miche\Downloads\mcstatusbot-0.2 (2)\mcstatusbot-0.2\node_modules\ws\lib\websocket.js:850:15)
    at TLSSocket.emit (events.js:327:22)
    at net.js:674:12
(node:9156) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:9156) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Restarting bot...

**Comment by tedztar** [comment]
it looks like you have not put your bot token in correctly

**Comment by tedztar** [comment]
@AlphaStrix717 have you gotten it working or is it still an issue?
