### ISSUE TITLE
UnhandledPromiseRejectionWarning:

### ISSUE THREAD

**Issue by stormlv368** [tedztar/mcstatusbot#47]
Hello, I have got the bot running. It has good connection with the server and works well. However, whenever I try and run __ANY__ command it returns the following and crashes:

```
(node:60884) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'user' of null
    at Object.exports.run (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\events\message.js:18:30)
    at Client.<anonymous> (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\mcbot.js:63:53)
    at Client.emit (events.js:315:20)
    at MessageCreateHandler.handle (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:105:65)
    at WebSocketConnection.onPacket (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:333:35)
    at WebSocketConnection.onMessage (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:296:17)
    at WebSocket.onMessage (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\storm\OneDrive\Desktop\mcstatusbot-0.2\node_modules\ws\lib\websocket.js:789:20)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:60884) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:60884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Thanks,
Lucas

**Comment by PicklePenger** [comment]
I have the same issue.
